---
title: "PS270 Final Project"
author: "Noah Everson"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Milestone One:
I would like explore some data on the Middle East and North Africa (MENA) data that would categorize the level of democracy in MENA countries and along with this, I would examine the scale of U.S. intervention in each country (could possibly be measured through U.S. financial aid to each country). Overall, I would use this to come to a conclusion on whether the majority of U.S. intervention in MENA countries is beneficial or disadvantageous since MENA intervention is often very controversial. 

Milestone Two:
	I would like to explore how U.S. intervention in terms and military and financial aid affects levels of democracy in the Middle East North Africa (MENA) region. My hypothesis is that when U.S. intervention occurs in MENA, it is often unsustainable. Therefore, it will increase democracy for a short time, but as soon as it is removed, the level of democracy will return to the previous level or drop even lower. The variables I would like to examine are the freedom scores of each country which are provided by the website freedomhouse.org. These scores reflect the civil liberties and political rights of citizens in each country. Additionally, I would like to look at data provided by the website foreignassistance.gov. This website contains records of all the foreign aid the U.S. government provides to other countries. Overall, I would like to see if there is some kind of correlation between the amount of aid provided to each country and the levels of democracy. I would like to use countries outside of the MENA region as a control to see whether U.S. aid itself has the same effect regardless of country or if the MENA region has a unique result from U.S. aid. If countries in the MENA region had higher levels of democracy after receiving aid, but then lower levels once the aid was removed or decreased significantly, then my hypothesis would seem accurate.  